# Docker composer version
version: '3'

# Define network name
networks:
  laravel:

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./apps:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      - maildev
    networks:
      - laravel

  mysql:
    image: mariadb:10.5.4-focal #mysql:5.6 mariadb:10.5.4-focal
    restart: unless-stopped
    user: 1000:985
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - .docker/data:/var/lib/mysql
      - ./docker/mysql/sql:/var/tmp #importer par mysql -uroot -p 
    environment:
      MYSQL_DATABASE: bdd
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: docker/php-7-4/Dockerfile
    user: 1000:985
    volumes:
      - ./apps:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
    depends_on:
      - maildev
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9092:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel

  maildev:
    image: djfarrelly/maildev
    container_name: JDG32_maildev
    ports:
      - "1026:25"
      - "1081:80"
    networks:
      - laravel

  adminer:
    image: adminer
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    ports:
      - 8888:8080
    networks:
      - laravel

  nodejs:
    build:
      context: .
      dockerfile: ./private/docker/config/nodejs/Dockerfile
    volumes:
      - ./apps:/var/www
  
  wkhtmltopdf:
    build:
      context: .
      dockerfile: ./private/wkhtmltopdf/Dockerfile
    ports:
      - 5555:5555
    networks:
      - laravel