# Docker composer version
version: '3'

# Define network name
networks:
  laravel:
    name: laravel_prod

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - ${DOCKER_PORT_NGINX}:80
    volumes:
      - ./apps:/var/www
      - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mariadb:10.5.4-focal #mysql:5.6 mariadb:10.5.4-focal
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/data:/var/lib/mysql
      - ./docker/mysql/sql:/var/tmp #importer par mysql -uroot -p 
    environment:
      MYSQL_DATABASE: ${DOCKER_DATABASE}
      MYSQL_USER: ${DOCKER_USERNAME}
      MYSQL_PASSWORD: ${DOCKER_PASSWORD}
      MYSQL_ROOT_PASSWORD : ${DOCKER_ROOT_PASSWORD}
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: docker/php-7-4/Dockerfile
    user: 1000:985
    volumes:
      - ./apps:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
    depends_on:
      - mysql

  nodejs:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    volumes:
      - ./apps:/var/www
    networks:
      - laravel